server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: BOOKGATEWAY
  cloud:
    gateway:
      routes:
      - id: BOOKINVENTORY
        uri: http://localhost:8081/
        predicates:
        - Path=/bookInventory/**
      - id: BOOKLENDING
        uri: http://localhost:8082/
        predicates:
        - Path=/bookLending/**
      # - id: bookPurchase
      #   uri: http://localhost:8083/
      #   predicates:
      #   - Path=/bookPurchase/**